name: CI

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - advanced/kernel-messaging
          - advanced/kernel-output
#          - advanced/serving-files
          - basics/datagrid
          - basics/hello-world
          - basics/signals
          - command-palette
          - commands
          - main-menu
          - react/react-widget
          - settings
          - state
          - widget-tracker/jupyter-widgets
          - widget-tracker/widgets
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check config files
      run: |
        diff basics/hello-world/tsconfig.json ${EXAMPLE_FOLDER}/tsconfig.json
        diff basics/hello-world/tslint.json ${EXAMPLE_FOLDER}/tslint.json
      env:
        EXAMPLE_FOLDER: ${{ matrix.example }}
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the Python dependencies
      run: python -m pip install jupyterlab
    - name: Install the NPM dependencies
      run: |
        cd ${EXAMPLE_FOLDER}
        jlpm
      env:
        EXAMPLE_FOLDER: ${{ matrix.example }}
    - name: Lint the files
      run: |
        cd ${EXAMPLE_FOLDER}
        jlpm run tslint:check
      env:
        EXAMPLE_FOLDER: ${{ matrix.example }}
    - name: Build and check by extension
      run: |
        cd ${EXAMPLE_FOLDER}
        jlpm run build
        jupyter labextension link .
        python -m jupyterlab.browser_check
      env:
        EXAMPLE_FOLDER: ${{ matrix.example }}

  build_serverextension:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the Python dependencies
      run: python -m pip install jupyterlab
    - name: Build and check extension as user
      run: |
        cd advanced/myserverextension
        pip install .
        jupyter lab build
        jupyter serverextension list
        jupyter labextension list
        python -m jupyterlab.browser_check
    - name: Clean extension installation
      run: |
        pip uninstall -y myextension
        jupyter lab clean
        jupyter serverextension list
        jupyter labextension list
    - name: Build and check extension as dev
      run: |
        pip install -e .
        jupyter serverextension enable --py myextension
        jupyter labextension link .
        jupyter serverextension list
        jupyter labextension list
        python -m jupyterlab.browser_check

  build_all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the Python dependencies
      run: python -m pip install jupyterlab
    - name: Bootstrap the jlpm deps
      run: jlpm
    - name: Build all the extensions
      run: |
        jlpm build-ext
        jlpm lint:check
        jlpm link-ext
        jlpm build-jlab
