name: CI

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - advanced/kernel-messaging
          - advanced/kernel-output
#          - advanced/serving-files
          - basics/datagrid
          - basics/hello-world
          - basics/signals
          - command-palette
          - commands
          - main-menu
          - react/react-widget
          - settings
          - state
          - widget-tracker/jupyter-widgets
          - widget-tracker/widgets
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check TS config
      run: |
        diff basics/hello-world/tsconfig.json ${EXAMPLE_FOLDER}/tsconfig.json
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the Python dependencies
      run: python -m pip install jupyterlab
    - name: Build and check by extension
      run: |
        cd ${EXAMPLE_FOLDER}
        jlpm && jlpm run build
        jupyter labextension link .
        python -m jupyterlab.browser_check
      env:
        EXAMPLE_FOLDER: ${{ matrix.example }}

  build_all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install the Python dependencies
      run: python -m pip install jupyterlab
    - name: Bootstrap the jlpm deps
      run: jlpm
    - name: Build all the extensions
      run: |
        jlpm build-ext
        jlpm lint:check
        jlpm link-ext
        jlpm build-jlab
